os: linux
dist: xenial

git:
  depth: 1

cache:
  yarn: true
  directories:
    - node_modules
    - $HOME/.composer/cache

jobs:
  include:
    - language: php
      php: 7.4
      install:
        - composer install
      script:
        - composer phing ci
    - language: node_js
      install:
        - nvm install
        - yarn install
      script:
        - yarn ci

notifications:
  webhooks:
    - https://coveralls.io/webhook
