os: linux
dist: xenial

git:
  depth: 1

php: 7.4

jobs:
  include:
    - cache:
        yarn: true
        directories:
          - node_modules
          - $HOME/.composer/cache
    - install:
        - yarn installX
        - composer install
    - script:
        - yarn ci
        - composer ci

notifications:
  webhooks:
    - https://coveralls.io/webhook

