os: linux
dist: xenial

git:
  depth: 1

language: node
php: 7.4

cache:
  yarn: true
  directories:
    - node_modules
    - $HOME/.composer/cache

install:
  - yarn install
  - composer install

jobs:
  include:
    - script:
        - yarn ci
        - composer phing ci

notifications:
  webhooks:
    - https://coveralls.io/webhook
