os: linux
dist: xenial

git:
  depth: 1

cache:
  yarn: true
  directories:
    - node_modules
    - $HOME/.composer/cache

install:
  - yarn install
  - composer install

jobs:
  include:
    - language: node
    - php: 7.4
    - script:
        - yarn ci
        - composer ci

notifications:
  webhooks:
    - https://coveralls.io/webhook

